version: '3'
 
services:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    networks:
      - helloworld-network
  
  service:
    image: service-image:0.0.1
    container_name: service-container
    build:
      context: ./springcloud-springboot3-gateway-secured_service
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - helloworld-network

  gateway:
    image: gateway-image
    container_name: gateway-container
    build:
      context: ./springcloud-springboot3-gateway-secured_routing
      dockerfile: Dockerfile
    environment:
      SERVICE_URL: http://service:9090
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://keycloak:8080/realms/helloworld-realm
    depends_on:
      - service
    ports:
      - 8762:8762
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8762/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - helloworld-network

networks:
  helloworld-network:
    name: helloworld-network-name