apiVersion: apps/v1
kind: Deployment
metadata:
  name: first
  labels:
    app: first
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first
  template:
    metadata:
      labels:
        app: first
    spec:
      containers:
      - name: first
        image: wisniewskikr/springcloud-transactions-saga-choreography_first:0.0.1
        ports:
        - containerPort: 8080
        env:
        - name: spring.kafka.producer.bootstrap-servers
          value: kafka:9092
        - name: spring.kafka.consumer.bootstrap-servers
          value: kafka:9092
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: first
spec:
  selector:
    app: first
  ports:
    - port: 8080
      targetPort: 8080