apiVersion: apps/v1
kind: Deployment
metadata:
  name: second
  labels:
    app: second
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second
  template:
    metadata:
      labels:
        app: second
    spec:
      containers:
      - name: second
        image: wisniewskikr/springcloud-transactions-saga-choreography_second:0.0.1
        ports:
        - containerPort: 8081
        env:
        - name: spring.kafka.producer.bootstrap-servers
          value: kafka:9092
        - name: spring.kafka.consumer.bootstrap-servers
          value: kafka:9092
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: second
spec:
  selector:
    app: second
  ports:
    - port: 8081
      targetPort: 8081