version: '3'

services:

  service-helloworld:
    image: service-helloworld-image
    build:
      context: ./service-helloworld
      dockerfile: Dockerfile
    environment:
      - spring.application.name=service-helloworld
      - management.endpoints.jmx.exposure.include=health,info,env,beans
      - management.endpoints.web.exposure.include=health,info,env,beans
      - service.helloworld.message=Hello World!
    ports:
      - 8080
    healthcheck:
      test: "exit 0"
    networks:
      - helloworld-network

networks:
  helloworld-network:
    name: helloworld-network