apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: wisniewskikr/springcloud-springboot3-circuitbreaker-r4j-apigateway_apigateway:0.0.1
          ports:
            - containerPort: 8762
          env:
            - name: service.url
              value: http://service:8082
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8762
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8762
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: apigateway
  ports:
    - port: 8762
      targetPort: 8762