# Spring
spring:
  application:
    name: service-helloworld
  config:
    import: optional:configserver:http://localhost:8888

# Port
server:
  port: ${port:8081}

# Actuator
management:
  endpoints:
    jmx:
      exposure:
        include: health,info,env,beans
    web:
      exposure:
        include: health,info,env,beans

# Eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: service-helloworld-2

# Logging
logging:
  file:
    name: C:/IT/logs/springcloud-simple-modules.log