apiVersion: apps/v1
kind: Deployment
metadata:
  name: first
  labels:
    app: first
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first
  template:
    metadata:
      labels:
        app: first
    spec:
      containers:
      - name: first
        image: wisniewskikr/springcloud-springboot3-basic_first:0.0.1
        ports:
        - containerPort: 8081
        env:
        - name: spring.application.name
          value: first
        - name: spring.config.import
          value: configserver:http://config:8888
        - name: LOKI_URL
          value: http://loki:3100
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: first
spec:
  selector:
    app: first
  ports:
    - port: 8081
      targetPort: 8081