apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-helloworld
  labels:
    app: deployment-helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: container-helloworld
  template:
    metadata:
      labels:
        app: container-helloworld
    spec:
      containers:
      - name: container-helloworld
        image: wisniewskikr/helloworld-image
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: spring.application.name
          value: "service-helloworld"
        - name: eureka.client.service-url.defaultZone
          value: "http://service-discovery-kubernetes:8761/eureka"
        - name: eureka.instance.prefer-ip-address
          value: "true"
        - name: management.endpoints.jmx.exposure.include
          value: "health,info,env,beans"
        - name: management.endpoints.web.exposure.include
          value: "health,info,env,beans"
        - name: spring.config.import
          value: "optional:configserver:http://service-config-kubernetes:8888"
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: service-helloworld-kubernetes
spec:
  selector:
    app: container-helloworld
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: service-helloworld-show
spec:
  type: NodePort
  selector:
    app: container-helloworld
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32100