version: '3'

services:

  service-discovery:
    image: service-discovery-image
    container_name: service-discovery-container
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    environment:
      - server.port=8761
      - eureka.client.fetch-registry=false
      - eureka.client.register-with-eureka=false
    ports:
      - 8761:8761
    networks:
      - helloworld-network

  service-config:
    image: service-config-image
    container_name: service-config-container
    build:
      context: ./service-config
      dockerfile: Dockerfile
    environment:
      - server.port=8888
      - spring.cloud.config.server.git.uri=https://github.com/wisniewskikr/springcloud-single-docker-compose
      - spring.cloud.config.server.git.clone-on-start=true
      - eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka
      - management.endpoints.jmx.exposure.include=health,info,env,beans
      - management.endpoints.web.exposure.include=health,info,env,beans
    ports:
      - 8888:8888
    depends_on:
      - service-discovery
    networks:
      - helloworld-network

  service-helloworld:
    image: service-helloworld-image
    container_name: service-helloworld-container
    build:
      context: ./service-helloworld
      dockerfile: Dockerfile
    environment:
      - server.port=8080
      - spring.config.import=optional:configserver:http://service-config:8888
      - eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka
      - management.endpoints.jmx.exposure.include=health,info,env,beans
      - management.endpoints.web.exposure.include=health,info,env,beans
    ports:
      - 8080:8080
    depends_on:
      - service-config
    networks:
      - helloworld-network

  service-gateway:
    image: service-gateway-image
    container_name: service-gateway-container
    build:
      context: ./service-gateway
      dockerfile: Dockerfile
    environment:
      - server.port=8762
      - spring.cloud.gateway.discovery.locator.enabled=true
      - spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true
      - eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka
      - management.endpoints.jmx.exposure.include=health,info,env,beans
      - management.endpoints.web.exposure.include=health,info,env,beans
    ports:
      - 8762:8762
    depends_on:
      - service-config
      - service-helloworld
    networks:
      - helloworld-network  

networks:
  helloworld-network:
    name: helloworld-network