version: '3'

services:

  service-discovery:
    image: service-discovery-image
    container_name: service-discovery-container
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    environment:
      - server.port=8761
      - eureka.client.fetch-registry=false
      - eureka.client.register-with-eureka=false
    ports:
      - 8761:8761
    networks:
      - helloworld-network

  service-config:
    image: service-config-image
    container_name: service-config-container
    build:
      context: ./service-config
      dockerfile: Dockerfile
    environment:
      - server.port=8888
      - spring.cloud.config.server.git.uri=https://github.com/wisniewskikr/springcloud-single-modules
      - spring.cloud.config.server.git.clone-on-start=true
      - eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka
      - management.endpoints.jmx.exposure.include=health,info,env,beans
      - management.endpoints.web.exposure.include=health,info,env,beans
    ports:
      - 8888:8888
    depends_on:
      - service-discovery
    networks:
      - helloworld-network  

networks:
  helloworld-network:
    name: helloworld-network