version: '3'

services:

  service-discovery:
    image: service-discovery-image
    container_name: service-discovery-container
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    environment:
      - server.port=8761
    ports:
      - 8761:8761
    networks:
      - helloworld-network

  service-config:
    image: service-config-image
    container_name: service-config-container
    build:
      context: ./service-config
      dockerfile: Dockerfile
    environment:
      - server.port=8888
      - eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka
    ports:
      - 8888:8888
    depends_on:
      - service-discovery
    networks:
      - helloworld-network  

networks:
  helloworld-network:
    name: helloworld-network