apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-helloworld-display
  labels:
    app: deployment-helloworld-display
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-helloworld-display
  template:
    metadata:
      labels:
        app: container-helloworld-display
    spec:
      containers:
      - name: container-helloworld-display
        image: wisniewskikr/helloworld-display-image
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: spring.application.name
          value: "service-helloworld-display"
        - name: server.port
          value: "8080"
        - name: eureka.client.service-url.defaultZone
          value: "http://service-discovery-kubernetes:8761/eureka"
        - name: eureka.instance.prefer-ip-address
          value: "true"
        - name: management.endpoints.jmx.exposure.include
          value: "health,info,env,beans"
        - name: management.endpoints.web.exposure.include
          value: "health,info,env,beans"
        - name: service.helloworld.storage.name
          value: "service-helloworld-storage"
        - name: spring.zipkin.baseUrl
          value: "http://zipkin:9411/"
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: service-helloworld-display-kubernetes
spec:
  selector:
    app: container-helloworld-display
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: service-helloworld-display-show
spec:
  type: NodePort
  selector:
    app: container-helloworld-display
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32400