#spring.application.name=hello-world
#spring.cloud.vault.kv.enabled=true
#spring.cloud.vault.authentication=TOKEN
#spring.cloud.vault.token=hvs.ZfmCRKbONHZFGspUV5trXKgU
#spring.cloud.vault.scheme=http
#spring.cloud.vault.host=127.0.0.1
#spring.cloud.vault.port=8200
#spring.cloud.vault.generic.backend=codeusingjava
#spring.cloud.vault.generic.default-context=credentials
#spring.config.import: vault://

#spring.cloud.vault.uri=http://localhost:8200
#spring.cloud.vault.token=hvs.ZfmCRKbONHZFGspUV5trXKgU
#spring.cloud.vault.generic.enabled=true
#spring.cloud.vault.generic.backend=codeusingjava
#spring.cloud.vault.generic.default-context=credentials

#spring.cloud.vault.authentication=TOKEN
#spring.cloud.vault.token=hvs.F0W3hHJtlrrCQzmLHlRTqTpY
#spring.cloud.vault.scheme=http
#spring.cloud.vault.kv.enabled=true
#spring.cloud.vault.generic.backend=hello-world
#spring.cloud.vault.generic.default-context=credentials

#app:
#  message: ${keystore_password}