# DATABASE CONFIGURATION

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: database
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: admin123
            - name: MYSQL_ROOT_PASSWORD
              value: my_secret_password
          ports:
            - containerPort: 3306
          livenessProbe:
            exec:
              command:
              - mysqladmin
              - ping
              - -h
              - "127.0.0.1"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - mysqladmin
              - ping
              - -h
              - "127.0.0.1"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306  
  clusterIP: None

---

# ZIPKIN CONFIGURATION

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:3.4.2
        ports:
        - containerPort: 9411
        livenessProbe:
          httpGet:
            path: /health
            port: 9411
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9411
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  type: NodePort
  selector:
    app: zipkin
  ports:
    - port: 9411
      targetPort: 9411
      nodePort: 30001

---

# BE CONFIGURATION

apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
  labels:
    app: be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - name: be
        image: wisniewskikr/springcloud-fe-thymeleaf-be-springboot-db-sql-mysql-zipkin_be:0.0.1
        ports:
        - containerPort: 8081
        env:
        - name: spring.datasource.url
          value: jdbc:mysql://mysql:3306/database
        - name: management.zipkin.tracing.endpoint
          value: http://zipkin:9411/api/v2/spans
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: be-service
spec:
  selector:
    app: be
  ports:
    - port: 8081
      targetPort: 8081

---

# FE CONFIGURATION

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
  labels:
    app: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: fe
        image: wisniewskikr/springcloud-fe-thymeleaf-be-springboot-db-sql-mysql-zipkin_fe:0.0.1
        ports:
        - containerPort: 8080
        env:
        - name: api.url
          value: http://be-service:8081
        - name: management.zipkin.tracing.endpoint
          value: http://zipkin:9411/api/v2/spans
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  type: NodePort
  selector:
    app: fe
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000