apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-kibana
  labels:
    app: deployment-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-kibana
  template:
    metadata:
      labels:
        app: container-kibana
    spec:
      containers:
      - name: container-kibana
        image: docker.elastic.co/kibana/kibana:8.3.3
        imagePullPolicy: Never
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch:9200"
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"

---

apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: container-kibana
  ports:
    - port: 5601
      targetPort: 5601