version: '3'
 
services:

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s 
    networks:
      - helloworld-network
#    volumes:
#      - dbdata:/var/lib/mysql

  config:
    image: config-image
    container_name: config-container
    build:
      context: ./springboot3-microservices-config-valut_SERVER
      dockerfile: Dockerfile
    environment:
      spring.cloud.config.server.git.default-label: docker-compose-vault
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8888:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - helloworld-network
  
  be:
    image: be-image:0.0.1
    container_name: be-container
    build:
      context: ./springboot3-microservices-config-valut_BE
      dockerfile: Dockerfile
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      spring.application.name: be
      spring.config.import: configserver:http://config:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - helloworld-network

  fe:
    image: fe-image:0.0.1
    container_name: fe-container
    build:
      context: ./springboot3-microservices-config-valut_FE
      dockerfile: Dockerfile
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      spring.application.name: fe
      spring.config.import: configserver:http://config:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - helloworld-network

networks:
  helloworld-network:
    name: helloworld-network-name