version: '3'

services:

  service-discovery:
    image: service-discovery-image
    container_name: service-discovery-container
    build:
      context: ./service-discovery
      dockerfile: Dockerfile-Fast
    environment:
      - spring.application.name=service-discovery
      - server.port=8761
      - eureka.client.fetch-registry=false
      - eureka.client.register-with-eureka=false
    ports:
      - 8761:8761
    healthcheck:
      test: "exit 0"
    networks:
      - helloworld-network

  service-batch:
    image: service-batch-image
    container_name: service-batch-container
    build:
      context: ./service-batch
      dockerfile: Dockerfile-Fast
    environment:
      - spring.application.name=service-batch
      - server.port=9090
      - eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka
      - management.endpoints.jmx.exposure.include=health,info,env,beans
      - management.endpoints.web.exposure.include=health,info,env,beans
      - spring.datasource.driver-class-name=org.h2.Driver
      - spring.datasource.url=jdbc:h2:mem:db-embedded;DB_CLOSE_DELAY=-1
      - spring.datasource.username=admin
      - spring.datasource.password=admin123
      - spring.h2.console.enabled=true
      - spring.h2.console.path=/console/
    ports:
      - 9090:9090
    healthcheck:
      test: "exit 0"
    depends_on:
      service-discovery:
        condition: service_healthy
    networks:
      - helloworld-network

  service-helloworld:
    image: service-helloworld-image
    container_name: service-helloworld-container
    build:
      context: ./service-helloworld
      dockerfile: Dockerfile-Fast
    environment:
      - spring.application.name=service-helloworld
      - server.port=8080
      - eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka
      - management.endpoints.jmx.exposure.include=health,info,env,beans
      - management.endpoints.web.exposure.include=health,info,env,beans
      - service.helloworld.message=Hello World
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"
    depends_on:
      service-batch:
        condition: service_healthy
    networks:
      - helloworld-network

  service-gateway:
    image: service-gateway-image
    container_name: service-gateway-container
    build:
      context: ./service-gateway
      dockerfile: Dockerfile-Fast
    environment:
      - spring.application.name=service-gateway
      - server.port=8762
      - eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka
      - management.endpoint.gateway.enabled=true
      - management.endpoints.web.exposure.include=gateway
      - spring.cloud.gateway.routes[0].id=service-helloworld
      - spring.cloud.gateway.routes[0].uri=lb://service-helloworld
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/**
    ports:
      - 8762:8762
    healthcheck:
      test: "exit 0"
    depends_on:
      service-helloworld:
        condition: service_healthy
    networks:
      - helloworld-network  

networks:
  helloworld-network:
    name: helloworld-network