version: "4"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
#    volumes:
#      - dbdata:/var/lib/mysql

  tempo:
    image: grafana/tempo:2.2.2
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./../../docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./../../docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "3110:3100"  # Tempo
      - "9411:9411" # zipkin

  loki:
    image: grafana/loki:3.3.2
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v2.46.0
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./../../docker/prometheus/prometheus-container.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.1.0
    volumes:
      - ./../../docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  be:
    image: be-image:0.0.1
    container_name: be-container
    build:
      context: ./../../springcloud-springboot3-full_BE
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/database
      management.zipkin.tracing.endpoint: http://tempo:9411/api/v2/spans
      LOKI_URL: http://loki:3100
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  fe:
    image: fe-image:0.0.1
    container_name: fe-container
    build:
      context: ./../../springcloud-springboot3-full_FE
      dockerfile: Dockerfile
    environment:
      api.url: http://be:8081
      management.zipkin.tracing.endpoint: http://tempo:9411/api/v2/spans
      LOKI_URL: http://loki:3100
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  gateway:
    image: gateway-image:0.0.1
    container_name: gateway-container
    build:
      context: ./../../springcloud-springboot3-full_GATEWAY
      dockerfile: Dockerfile
    environment:
      spring_cloud_gateway_routes_0_id: forward_route_to_fe
      spring_cloud_gateway_routes_0_uri: http://fe:8080
      spring_cloud_gateway_routes_0_predicates_0: Path=/**
      management.zipkin.tracing.endpoint: http://tempo:9411/api/v2/spans
      LOKI_URL: http://loki:3100
    depends_on:
      - fe
    ports:
      - 8762:8762
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8762/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s