version: "4"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
#    volumes:
#      - dbdata:/var/lib/mysql

  second:
    image: second-image:0.0.1
    container_name: second-container
    build:
      context: ./../springcloud-springboot3-basic_SECOND
      dockerfile: Dockerfile
    environment:
      spring.application.name: second
    depends_on:
      discovery:
        condition: service_healthy
    ports:
      - 8082:8082
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  first:
    image: first-image:0.0.1
    container_name: first-container
    build:
      context: ./../springcloud-springboot3-basic_FIRST
      dockerfile: Dockerfile
    environment:
      spring.application.name: first
    depends_on:
      discovery:
        condition: service_healthy
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s