apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms1
  template:
    metadata:
      labels:
        app: ms1
    spec:
      containers:
        - name: ms1
          image: wisniewskikr/springcloud-springboot3-loadbalancing-clientside_ms1:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: eureka.client.service-url.defaultZone
              value: http://discovery:8761/eureka
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: ms1
spec:
  selector:
    app: ms1
  ports:
    - port: 8080
      targetPort: 8080