apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-discovery
  labels:
    app: deployment-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-discovery
  template:
    metadata:
      labels:
        app: container-discovery
    spec:
      containers:
      - name: container-discovery
        image: wisniewskikr/springcloud-single-kubernetes-service-discovery-image
        ports:
        - containerPort: 8761
        env:
        - name: spring.application.name
          value: "service-discovery"
        - name: server.port
          value: "8761"
        - name: eureka.client.fetch-registry
          value: "false"
        - name: eureka.client.register-with-eureka
          value: "false"
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 55
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 55
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: service-discovery
spec:
  selector:
    app: container-discovery
  ports:
    - port: 8761
      targetPort: 8761