apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-gateway
  labels:
    app: deployment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-gateway
  template:
    metadata:
      labels:
        app: container-gateway
    spec:
      containers:
      - name: container-gateway
        image: wisniewskikr/springcloud-single-kubernetes-service-gateway-image
        ports:
        - containerPort: 8762
        env:
        - name: spring.application.name
          value: "service-gateway"
        - name: server.port
          value: "8762"
        - name: eureka.client.service-url.defaultZone
          value: "http://service-discovery:8761/eureka"
        - name: management.endpoints.jmx.exposure.include
          value: "health,info,env,beans"
        - name: management.endpoints.web.exposure.include
          value: "health,info,env,beans"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0__ID
          value: "service-helloworld"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0__URI
          value: "lb://service-helloworld"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0__PREDICATES_0
          value: "Path=/service-helloworld**"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0__FILTERS_0
          value: "RewritePath=/service-helloworld,/"
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8762
            initialDelaySeconds: 55
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8762
            initialDelaySeconds: 55
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: service-gateway
spec:
  type: NodePort
  selector:
    app: container-gateway
  ports:
    - protocol: TCP
      port: 8762
      targetPort: 8762
      nodePort: 31000