services:

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s 
    networks:
      - helloworld-network
#    volumes:
#      - dbdata:/var/lib/mysql

  discovery:
    image: discovery-image
    container_name: discovery-container
    build:
      context: ./springcloud-springboot3-loadbalancing-clientside_DISCOVERY
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8761:8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - helloworld-network
  
  be:
    image: be-image:0.0.1
    build:
      context: ./springcloud-springboot3-loadbalancing-clientside_MS2
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/database
      eureka.client.service-url.defaultZone: http://discovery:8761/eureka
    depends_on:
      - discovery
    deploy:
      replicas: 2
    ports:
      - 0:80
    networks:
      - helloworld-network

  fe:
    image: fe-image:0.0.1
    build:
      context: ./springcloud-springboot3-loadbalancing-clientside_MS1
      dockerfile: Dockerfile
    environment:
      eureka.client.service-url.defaultZone: http://discovery:8761/eureka
    depends_on:      
      - discovery
      - be
    deploy:
      replicas: 2
    ports:
      - 0:80
    networks:
      - helloworld-network

  gateway:
    image: gateway-image
    container_name: gateway-container
    build:
      context: ./springcloud-loadbalancing-serverside_ROUTING
      dockerfile: Dockerfile
    environment:
      eureka.client.service-url.defaultZone: http://discovery:8761/eureka
    depends_on:
      - discovery
      - be
      - fe
    ports:
      - 8060:8060
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8060/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - helloworld-network

networks:
  helloworld-network:
    name: helloworld-network-name