version: '3'

services:
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    container_name: elasticsearch-container
    ports:
        - 9200:9200
    environment:
        discovery.type: single-node
        xpack.security.enabled: false
    networks:
      - helloworld-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.1
    container_name: kibana-container
    ports:
        - 5601:5601
    restart: on-failure
    depends_on:
        - elasticsearch
    networks:
      - helloworld-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.1
    container_name: filebeat-container
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
        - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro        # Configuration file
        - /var/lib/docker/containers:/var/lib/docker/containers:ro                  # Docker logs
        - /var/run/docker.sock:/var/run/docker.sock:ro                              # Additional information about containers
    user: root                                                                      # Allow access to log files and docker.sock
    restart: on-failure
    depends_on:
        - kibana
    networks:
      - helloworld-network  

networks:
  helloworld-network:
    name: helloworld-network
    external: true