version: '3'

services: 
      
  zipkin:
    image: openzipkin/zipkin:2
    container_name: zipkin-container
    ports:
      - 9411:9411    
    networks:
      - helloworld-network  
  
networks:
  helloworld-network:
    name: helloworld-network
    external: true