version: '3'

services:

  service-helloworld-be:
    image: service-helloworld-be-image
    build:
      context: ./service-helloworld-be
      dockerfile: Dockerfile-Fast
    environment:
      - spring.application.name=service-helloworld-be
      - server.port=9090
      - eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka
      - management.endpoints.jmx.exposure.include=health,info,env,beans
      - management.endpoints.web.exposure.include=health,info,env,beans
      - spring.config.import=optional:configserver:http://service-config:8888
      - management.tracing.sampling.probability=1.0
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - 9090
    healthcheck:
      test: "exit 0"
    networks:
      - helloworld-network

  service-helloworld-fe:
    image: service-helloworld-fe-image
    container_name: service-helloworld-fe-container
    build:
      context: ./service-helloworld-fe
      dockerfile: Dockerfile-Fast
    environment:
      - spring.application.name=service-helloworld-fe
      - server.port=8080
      - eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka
      - management.endpoints.jmx.exposure.include=health,info,env,beans
      - management.endpoints.web.exposure.include=health,info,env,beans
      - service.helloworld.be.name=service-helloworld-be
      - management.tracing.sampling.probability=1.0
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"
    networks:
      - helloworld-network   

networks:
  helloworld-network:
    name: helloworld-network
    external: true