apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-elasticsearch
  labels:
    app: deployment-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-elasticsearch
  template:
    metadata:
      labels:
        app: container-elasticsearch
    spec:
      containers:
      - name: container-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
        imagePullPolicy: Never
        ports:
        - containerPort: 9200
        env:
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "false"
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: eleasticsearch
spec:
  selector:
    app: container-elasticsearch
  ports:
    - port: 9200
      targetPort: 9200

---

apiVersion: v1 
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
spec: 
  capacity: 
    storage: 50M
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/share/elasticsearch/data
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
spec: 
  volumeName: elasticsearch-pv 
  accessModes: 
    - ReadWriteOnce
  storageClassName: standard
  resources: 
    requests: 
      storage: 50M