global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'first'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['first:8081']
  - job_name: 'second'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['second:8082']
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8762']