# Spring
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wisniewskikr/springcloud-single-modules
          clone-on-start: true

# Actuator
management:
  endpoints:
    jmx:
      exposure:
        include: health,info,env,beans
    web:
      exposure:
        include: health,info,env,beans

# Eureka
eureka:
  client:
    service-url:
      default-zone: http://service-discovery:8761/eureka