# Service Name
spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: MS1
            uri: http://localhost:9090
            predicates:
              - Path=/api/ms1/**
          - id: MS2
            uri: lb://MS2
            predicates:
              - Path=/api/ms2/**


# Server Port
server:
  port: 8080