# Service Name
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: MS1
          uri: http://localhost:9090
          predicates:
            - Path=/api/ms1/**
        - id: MS2
          uri: http://localhost:63989
          predicates:
            - Path=/api/ms2/**


# Server Port
server:
  port: 8080