services:

  discovery:
    image: discovery-image
    container_name: discovery-container
    build:
      context: ./../springcloud-springboot3-loadbalancing-serverside_DISCOVERY
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - helloworld-network
  
  ms1:
    image: ms1-image:0.0.1
    build:
      context: ./../springcloud-springboot3-loadbalancing-serverside_MS1
      dockerfile: Dockerfile
    environment:
      eureka.client.service-url.defaultZone: http://discovery:8761/eureka
      baseurl.ms2: http://gateway:8080/api/ms2
    depends_on:
      discovery:
        condition: service_healthy
    ports:
      - 9090:9090
    networks:
      - helloworld-network

  ms2:
    image: ms2-image:0.0.1
    build:
      context: ./../springcloud-springboot3-loadbalancing-serverside_MS2
      dockerfile: Dockerfile
    environment:
      eureka.client.service-url.defaultZone: http://discovery:8761/eureka
    depends_on:
      discovery:
        condition: service_healthy
    deploy:
      replicas: 2
    ports:
      - 0:80
    networks:
      - helloworld-network

  gateway:
    image: gateway-image:0.0.1
    build:
      context: ./../springcloud-springboot3-loadbalancing-serverside_GATEWAY
      dockerfile: Dockerfile
    environment:
      eureka.client.service-url.defaultZone: http://discovery:8761/eureka
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES[0]_ID: MS1
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES[0]_URI: http://ms1:9090
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES[0]_PREDICATES[0]: Path=/api/ms1/**
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES[1]_ID: MS2
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES[1]_URI: lb://MS2
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES[1]_PREDICATES[0]: Path=/api/ms2/**
    depends_on:
      discovery:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - helloworld-network

networks:
  helloworld-network:
    name: helloworld-network-name