# Spring
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

# Actuator
management:
  endpoints:
    jmx:
      exposure:
        include: health,info,env,beans
    web:
      exposure:
        include: health,info,env,beans

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://service-discovery:8761/eureka}