apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-discovery
  labels:
    app: deployment-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-discovery
  template:
    metadata:
      labels:
        app: container-discovery
    spec:
      containers:
      - name: container-discovery
        image: discovery-image
        imagePullPolicy: Never
        ports:
        - containerPort: 8761
        env:
        - name: spring.application.name
          value: "service-discovery"
        - name: server.port
          value: "8761"
        - name: eureka.client.fetch-registry
          value: "false"
        - name: eureka.client.register-with-eureka
          value: "false"
        - name: eureka.instance.prefer-ip-address
          value: "true"
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 15
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 15
      restartPolicy: Always

---

---

apiVersion: v1
kind: Service
metadata:
  name: service-discovery-kubernetes
spec:
  selector:
    app: container-discovery
  ports:
    - port: 8761
      targetPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: service-discovery-show
spec:
  type: NodePort
  selector:
    app: container-discovery
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30001