apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-gateway
  labels:
    app: deployment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-gateway
  template:
    metadata:
      labels:
        app: container-gateway
    spec:
      containers:
      - name: container-gateway
        image: wisniewskikr/gateway-image
        imagePullPolicy: Never
        ports:
        - containerPort: 8762
        env:
        - name: spring.application.name
          value: "service-gateway"
        - name: server.port
          value: "8762"
        - name: eureka.client.service-url.defaultZone
          value: "http://service-discovery-kubernetes:8761/eureka"
        - name: eureka.instance.prefer-ip-address
          value: "true"
        - name: management.endpoints.jmx.exposure.include
          value: "health,info,env,beans"
        - name: management.endpoints.web.exposure.include
          value: "health,info,env,beans"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
          value: "service-helloworld"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
          value: "lb://service-helloworld"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
          value: "Path=/**"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0
          value: "RewritePath=/,/"
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8762
            initialDelaySeconds: 15
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8762
            initialDelaySeconds: 15
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: service-gateway-show
spec:
  type: NodePort
  selector:
    app: container-gateway
  ports:
    - protocol: TCP
      port: 8762
      targetPort: 8762
      nodePort: 30003