version: '3'

services:

  service-helloworld-storage:
    image: service-helloworld-storage-image
    build:
      context: ./service-helloworld-storage
      dockerfile: Dockerfile
    environment:
      - spring.application.name=service-helloworld-storage
      - management.endpoints.jmx.exposure.include=health,info,env,beans
      - management.endpoints.web.exposure.include=health,info,env,beans
      - service.helloworld.message=Hello World
    ports:
      - 8081
    healthcheck:
      test: "exit 0"
    depends_on:
      service-config:
        condition: service_healthy
    networks:
      - helloworld-network  

  service-helloworld-display:
    image: service-helloworld-display-image
    container_name: service-helloworld-display-container
    build:
      context: ./service-helloworld-display
      dockerfile: Dockerfile
    environment:
      - spring.application.name=service-helloworld-display
      - server.port=8080
      - management.endpoints.jmx.exposure.include=health,info,env,beans
      - management.endpoints.web.exposure.include=health,info,env,beans
      - service.helloworld.storage.name=service-helloworld-storage
      - service.helloworld.storage.url=service-helloworld-storage:8081
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"
    depends_on:
      service-discovery:
        condition: service_healthy
    networks:
      - helloworld-network

networks:
  helloworld-network:
    name: helloworld-network