version: '3'

services:

  service-helloworld-storage:
    image: service-helloworld-storage-image
    container_name: service-helloworld-storage-container
    build:
      context: ./service-helloworld-storage
      dockerfile: Dockerfile-Fast
    environment:
      - spring.application.name=service-helloworld-storage
      - server.port=8081
      - management.endpoints.jmx.exposure.include=health,info,env,beans
      - management.endpoints.web.exposure.include=health,info,env,beans
      - service.helloworld.message=Hello World
    ports:
      - 8081:8081
    healthcheck:
      test: "exit 0"
    networks:
      - helloworld-network  

networks:
  helloworld-network:
    name: hello-network