version: '3'

services:

  service-helloworld-display:
    image: service-helloworld-display-image
    container_name: service-helloworld-display-container
    build:
      context: ./service-helloworld-display
      dockerfile: Dockerfile-Fast
    environment:
      - spring.application.name=service-helloworld-display
      - server.port=8080
      - management.endpoints.jmx.exposure.include=health,info,env,beans
      - management.endpoints.web.exposure.include=health,info,env,beans
      - service.helloworld.storage.name=service-helloworld-storage
      - service.helloworld.storage.url=http://service-helloworld-storage:8081
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"
    networks:
      - helloworld-network

networks:
  helloworld-network:
    external:
      name: hello-network