apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-zipkin
  labels:
    app: deployment-zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-zipkin
  template:
    metadata:
      labels:
        app: container-zipkin
    spec:
      containers:
      - name: container-zipkin
        image: openzipkin/zipkin
        ports:
        - containerPort: 9411

---

apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  selector:
    app: container-zipkin
  ports:
    - port: 9411
      targetPort: 9411