# Spring
spring:
  application:
    name: service-helloworld-display
  config:
    import: optional:configserver:http://localhost:8888

# Port
server:
  port: ${port:8080}

# Actuator
management:
  endpoints:
    jmx:
      exposure:
        include: health,info,env,beans
    web:
      exposure:
        include: health,info,env,beans

# Eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: service-helloworld-1

# Feign
service:
  helloworld:
    storage:
      name: service-helloworld-storage